<?php
/**
 * Jericho Comms - Information-theoretically secure communications
 * Copyright (c) 2013-2017  Joshua M. David
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation in version 3 of the License.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see [http://www.gnu.org/licenses/].
 */


/**
 * To edit the valid number of users for this chat group, change the
 * $numberOfUsers variable. This must be a value between 2 - 7 inclusive.
 *
 * The server key is used to sign all data going to or from the server using
 * the Skein-512 hash. This key is ideally generated by the TRNG in the
 * client application and exported for each user with their one-time pads
 * so they can connect to the server to send/receive messages.
 *
 * Make sure the server key is random hexadecimal symbols (0-9, a-f) of 128
 * hexadecimal symbols in length which is a 512 bit key. The client program can
 * generate a truly random 512 bit server key for you. This can be done after
 * the one-time pads have been generated. From there you can copy and paste it
 * into this configuration file.
 *
 * You can also change the MySQL database credentials as required.
 *
 * If the client is having trouble connecting, try setting the testResponseHeaders
 * value to true. This will enable debug messages to be sent back with the responses
 * which are viewable in the browser's development tools or Firebug.
 */

// Valid users for this chat group (currently only 2, 3, 4, 5, 6 or 7 are supported)
$numberOfUsers = 2;

// The 512 bit server key in lowercase hexadecimal symbols
$serverKey = '89975057bac787e526aba890440dd89f95f2ea14a1779dcd3ff4bac215418a7566dafb5bf19417ec6d152f636ba8eb3ac4bb823086da8541798f67c3a1055d2e';

// Database config - Credentials for PHP to access the MySQL server database
$databaseConfig = array(

	// Database password
	'password' => 'covert',

	// Database username (generally default of root will be fine so you probably do not need to edit this)
	'username' => 'root',

	// The hostname (generally MySQL is on the same machine so you probably do not need to edit this)
	'hostname' => '127.0.0.1',

	// The port (generally 3306 is the default MySQL port so you probably do not need to edit this)
	'port' => 3306,

	// The socket for the connection if not using hostname and port (generally not required,
	// only add if required if not using a VPS and your webhost does not allow ports)
	'unix_socket' => '',

	// Name of the database (generally default is fine, unless you are making a new
	// chat group on the server and modified the SQL installation script as well)
	'database' => 'jericho',
);

// Application config - some settings specific to testing
$applicationConfig = array(

	// Enables messages in the HTTP 404 error responses for debug purposes - make sure this is false for a live server!
	'testResponseHeaders' => false
);
